In [143]:
import numpy as np 

In [144]:
X=np.array(([6,4],[6,5],[5,5],[4,4],[4,5],[3,4],[4,2],[1,1],[1,4],[1,6],[1,8],[3,7]), dtype=float)
Y=np.array(([0],[0],[0],[0],[0],[0],[1],[1],[1],[1],[1],[1]), dtype=float)
learn_rate=0.005

In [145]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [146]:
def sigmoid_derivative(s):
    return s * (1 - s)

In [150]:
class NeuralNetwork:
    def __init__(self,x,y):
        self.input = x
        self.weights_i_h= np.random.rand(self.input.shape[1],4)
        self.weights_h_o = np.random.rand(4,1)
        self.y = y
        self.output = np. zeros(y.shape)
        
    def forward_propagation(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights_i_h))
        self.layer2 = sigmoid(np.dot(self.layer1, self.weights_h_o))
        return self.layer2
        
    def back_propagation(self):
        delta_weights_h_o = np.dot(self.layer1.T, 2*(self.y -self.output)*sigmoid_derivative(self.output))
        delta_weights_i_h = np.dot(self.input.T, np.dot(2*(self.y -self.output)*sigmoid_derivative(self.output), self.weights_h_o.T)*sigmoid_derivative(self.layer1))
    
        self.weights_i_h += learn_rate*delta_weights_i_h
        self.weights_h_o += learn_rate*delta_weights_h_o

    def train(self,x,y):
        self.output = self.forward_propagation()
        self.back_propagation()
        
    def predict(self, inputs):
        inputs = inputs.astype(float)
        self.layer1 = sigmoid(np.dot(inputs, self.weights_i_h))
        self.layer2 = sigmoid(np.dot(self.layer1, self.weights_h_o))
        return self.layer2

In [154]:
NN = NeuralNetwork(X,Y)
for epoch in range(100): 
    NN.train(X,Y)
print ("Input : \n" + str(X))
print ("Actual Output: \n" + str(Y))
print ("Predicted Output: \n" + str(NN.forward_propagation()))
print ("MSE:" + str(np.mean(np.square(Y - NN.forward_propagation()))))

Input : 
[[6. 4.]
 [6. 5.]
 [5. 5.]
 [4. 4.]
 [4. 5.]
 [3. 4.]
 [4. 2.]
 [1. 1.]
 [1. 4.]
 [1. 6.]
 [1. 8.]
 [3. 7.]]
Actual Output: 
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
Predicted Output: 
[[0.50014344]
 [0.50127725]
 [0.50849489]
 [0.51523701]
 [0.51618355]
 [0.52374373]
 [0.51407568]
 [0.55022711]
 [0.54374244]
 [0.54276407]
 [0.54323281]
 [0.52628526]]
MSE:0.23790893153069978


In [155]:
input_one = str(input("X1: "))
input_two = str(input("X2: "))
print("New Index: ",input_one,input_two)
print("Output: ")
print(NN.predict(np.array([input_one, input_two])))

X1: 5
X2: 5
New Index:  5 5
Output: 
[0.50849489]
